import SwiftUI
import SwiftData
import CoreLocation

struct RootView: View {
 @Environment(\.modelContext) private var context; @EnvironmentObject var app:AppController; @State private var tab=0
 var body: some View { TabView(selection:$tab) { HomeView().tabItem{Label("Home",systemImage:"house.fill")}.tag(0); ActivityView().tabItem{Label("Activity",systemImage:"clock")}.tag(1); ReportsView().tabItem{Label("Reports",systemImage:"chart.bar")}.tag(2); SettingsView().tabItem{Label("Settings",systemImage:"gear")}.tag(3) }
 .onAppear { if let s=(try? context.fetch(FetchDescriptor<WorkSession>(predicate:#Predicate{$0.status == "active"},sortBy:[SortDescriptor(\WorkSession.start,order:.reverse)])).first) { app.location.start(session:s) } }
 .onOpenURL { url in let store=SessionStore(context:context,location:app.location); if url.host == "start" { store.start(source:"Amazon Flex") }; if url.host == "end" { store.end() } } }
}
struct HomeView: View {
 @Environment(\.modelContext) private var context; @EnvironmentObject var app:AppController; @Query(sort:\WorkSession.start, order:.reverse) private var sessions:[WorkSession]; @State private var showSource=false; @State private var source="Amazon Flex"
 var active:WorkSession? { sessions.first(where:{$0.status=="active"}) }
 var body: some View { NavigationStack { ScrollView { VStack(spacing:18) { Text(active == nil ? "READY TO WORK" : "🟢 WORKING").font(.title2.bold()); if let s=active { ActiveCard(s:s) } else { Button{showSource=true} label:{ Text("START WORK").font(.title2.bold()).frame(maxWidth:.infinity).padding().background(.green,in:RoundedRectangle(cornerRadius:16)).foregroundStyle(.white) } .buttonStyle(.plain); Button("Quick Start: Amazon Flex"){ SessionStore(context:context,location:app.location).start(source:"Amazon Flex") }.buttonStyle(.bordered) } }.padding() }.navigationTitle("FabVex Mileage") }.confirmationDialog("What are you working?",isPresented:$showSource,titleVisibility:.visible){ Button("Amazon Flex"){ SessionStore(context:context,location:app.location).start(source:"Amazon Flex") }; Button("DoorDash"){ SessionStore(context:context,location:app.location).start(source:"DoorDash") }; Button("3D Printing"){ SessionStore(context:context,location:app.location).start(source:"3D Printing") }; Button("Other"){ SessionStore(context:context,location:app.location).start(source:"Other") }; Button("Cancel",role:.cancel){} } }
}
struct ActiveCard:View { @Environment(\.modelContext) private var context; @EnvironmentObject var app:AppController; let s:WorkSession; var body:some View { VStack(alignment:.leading,spacing:12){ Text(s.source).font(.headline); Text(String(format:"%.1f mi",s.finalMiles)).font(.system(size:44,weight:.bold)); Text("Started \(s.start.formatted(date:.omitted,time:.shortened)) • \(s.confidence) confidence").foregroundStyle(.secondary); Button("END WORK"){ SessionStore(context:context,location:app.location).end() }.frame(maxWidth:.infinity).padding().background(.red,in:RoundedRectangle(cornerRadius:14)).foregroundStyle(.white); NavigationLink("Details",destination:SessionDetailView(session:s)) }.padding().background(.thinMaterial,in:RoundedRectangle(cornerRadius:20)) } }
struct ActivityView:View { @Query(sort:\WorkSession.start,order:.reverse) private var sessions:[WorkSession]; var body:some View{NavigationStack{List(sessions){s in NavigationLink(destination:SessionDetailView(session:s)){VStack(alignment:.leading){Text(s.source).font(.headline);Text("\(s.start.formatted(date:.abbreviated,time:.shortened)) • \(s.finalMiles,specifier:"%.1f") mi • \(s.status)").font(.subheadline).foregroundStyle(.secondary)}}}.navigationTitle("Activity")}}}
struct SessionDetailView:View { @Bindable var session:WorkSession; var body:some View{Form{Section("Mileage"){LabeledContent("GPS filtered",value:String(format:"%.1f mi",session.filteredMiles));LabeledContent("Reconstructed",value:String(format:"%.1f mi",session.reconstructedMiles));LabeledContent("User adjustment",value:String(format:"%.1f mi",session.userAdjustment));LabeledContent("Final",value:String(format:"%.1f mi",session.finalMiles));TextField("Notes",text:$session.notes)};Section("Earnings"){TextField("Actual pay",value:$session.actualPay,format:.currency(code:"USD")).keyboardType(.decimalPad);TextField("Pay adjustment",value:$session.payAdjustment,format:.currency(code:"USD")).keyboardType(.decimalPad)}}.navigationTitle("Session")}}
struct ReportsView:View {
 @Query private var sessions:[WorkSession]; @Query private var expenses:[Expense]; @State private var shareURL:URL?
 var body:some View{NavigationStack{List{Section("Today"){stat("Mileage",sessions.filter{Calendar.current.isDateInToday($0.start)}.reduce(0){$0+$1.finalMiles},"mi");stat("Work hours",sessions.filter{Calendar.current.isDateInToday($0.start)}.reduce(0){$0+($1.end?.timeIntervalSince($1.start) ?? 0)/3600},"h");stat("Income",sessions.filter{Calendar.current.isDateInToday($0.start)}.compactMap{$0.actualPay}.reduce(0,+),"USD")};Section("Export"){Button("Export CSV"){share(data:ReportExporter.csv(sessions:sessions,expenses:expenses),ext:"csv")};Button("Export PDF"){share(data:ReportExporter.pdf(sessions:sessions,expenses:expenses),ext:"pdf")};Text("Exports are recordkeeping summaries. Actual expenses and estimated fuel remain separate in the data model.").font(.footnote).foregroundStyle(.secondary)}}.navigationTitle("Reports").sheet(item:$shareURL){url in ShareSheet(items:[url])}}}
 func stat(_ n:String,_ v:Double,_ u:String)->some View{HStack{Text(n);Spacer();Text(u=="USD" ? String(format:"$%.2f",v) : String(format:"%.1f %@",v,u)).bold()}}
 func share(data:Data,ext:String){let url=FileManager.default.temporaryDirectory.appendingPathComponent("FabVexMileage-Report.\(ext)");try? data.write(to:url);shareURL=url}
}
struct ShareSheet:UIViewControllerRepresentable{let items:[Any];func makeUIViewController(context:Context)->UIActivityViewController{UIActivityViewController(activityItems:items,applicationActivities:nil)};func updateUIViewController(_ vc:UIActivityViewController,context:Context){}}
struct SettingsView:View { @Environment(\.modelContext) private var context; @Query private var settings:[AppSettings]; @Query private var vehicles:[Vehicle]; var body:some View{NavigationStack{Form{Section("Tracking"){Text("Manual start/end is the default. Background GPS is enabled while a session is active.");Picker("GPS retention",selection:.constant("90 days")){Text("30 days");Text("90 days");Text("1 year");Text("Forever");Text("Mileage only")};Picker("Stationary reminder",selection:.constant(30)){Text("Off").tag(0);Text("10 min").tag(10);Text("30 min").tag(30);Text("60 min").tag(60)}};Section("Vehicle"){if vehicles.isEmpty{Button("Add Primary Vehicle"){context.insert(Vehicle())}}else{ForEach(vehicles){v in Text("\(v.name) • \(v.mpg,specifier:"%.1f") MPG")}}};Section("Home Base"){Text("Set Home Base from the first location permission flow or add it in a future location picker.").foregroundStyle(.secondary)}}.navigationTitle("Settings")}}}
